version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:3000"
    working_dir: /app/frontend
    command: ["npm", "start"]
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_started

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "8080:8080"
    working_dir: /app/server
    command: ["npm", "start"]
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_started

  redis:
    image: redis
    command: --port 4501
    ports:
      - "4501:4501"
    env_file:
    - .env